'use client'

import { useEffect, useMemo, useState } from 'react'

type Kind = 'equipment' | 'service'
type Source = 'rooted' | 'client'
type Item = { name: string; quantity: number; unit: number; source: Source; kind: Kind }
type Client = { name: string; phone: string; description: string; items: Item[] }
type CatalogEntry = { name: string; unit: number }

const warranty = 'Materiais fornecidos pela Rooted Informática possuem garantia conforme as condições do fabricante e a legislação aplicável.\nA mão de obra possui garantia legal de 90 dias sobre a execução do serviço, observadas as condições legais aplicáveis.\nMateriais fornecidos pelo cliente permanecem sujeitos às condições de garantia do respectivo fabricante ou fornecedor, sem prejuízo das responsabilidades legais relativas aos serviços prestados.'
const emptyItem = (): Item => ({ name: '', quantity: 1, unit: 0, source: 'rooted', kind: 'equipment' })
const API_URL = process.env.NEXT_PUBLIC_PHP_API_URL || ''
const products: CatalogEntry[] = [
  { name: 'Câmera de Segurança', unit: 290 },
  { name: 'Motor de Portão Rossi DZ Nano Turbo', unit: 950 },
  { name: 'Fonte 12V 10A', unit: 122.71 },
  { name: 'HD 1TB para DVR', unit: 350 },
  { name: 'Kit conectores e acessórios', unit: 80 },
]
const services: CatalogEntry[] = [
  { name: 'Instalação e configuração de câmera', unit: 150 },
  { name: 'Diagnóstico de motor de portão', unit: 150 },
  { name: 'Instalação e configuração de DVR', unit: 300 },
  { name: 'Visita técnica', unit: 150 },
]
const demoItems: Item[] = [
  { name: 'Câmera de Segurança', quantity: 4, unit: 290, source: 'rooted', kind: 'equipment' },
  { name: 'Fonte 12V 10A', quantity: 1, unit: 122.71, source: 'rooted', kind: 'equipment' },
  { name: 'HD 1TB para DVR', quantity: 1, unit: 350, source: 'rooted', kind: 'equipment' },
  { name: 'Kit conectores e acessórios', quantity: 1, unit: 80, source: 'rooted', kind: 'equipment' },
  { name: 'Instalação e configuração de câmera', quantity: 4, unit: 150, source: 'rooted', kind: 'service' },
  { name: 'Diagnóstico de motor de portão', quantity: 1, unit: 150, source: 'rooted', kind: 'service' },
  { name: 'Instalação e configuração de DVR', quantity: 1, unit: 300, source: 'rooted', kind: 'service' },
  { name: 'Visita técnica', quantity: 1, unit: 150, source: 'rooted', kind: 'service' },
]
const initialClients: Client[] = [
  { name: 'Cliente demonstração completo', phone: '(41) 99999-0000', description: 'Instalação e configuração de sistema de segurança, câmeras, DVR e diagnóstico de motor de portão.', items: demoItems },
  { name: 'Cliente de teste - Empresa Exemplo', phone: '(41) 99999-0001', description: 'Serviço de teste para geração do orçamento.', items: [] },
  { name: 'Cliente de teste - Residencial', phone: '(41) 99999-0002', description: 'Serviço residencial de teste.', items: [] },
]

export default function Home() {
  const [client, setClient] = useState(''); const [os, setOs] = useState(''); const [responsible, setResponsible] = useState('Roberto Jean Martins'); const [phone, setPhone] = useState(''); const [payment, setPayment] = useState('PIX / Mercado Pago'); const [description, setDescription] = useState(''); const [markup, setMarkup] = useState(30); const [travel, setTravel] = useState(0); const [items, setItems] = useState<Item[]>([emptyItem()]); const [status, setStatus] = useState('Rascunho'); const [saved, setSaved] = useState(false); const [history, setHistory] = useState<any[]>([]); const [message, setMessage] = useState(''); const [showClientBase, setShowClientBase] = useState(false); const [showProductBase, setShowProductBase] = useState(false); const [showServiceBase, setShowServiceBase] = useState(false); const [clients, setClients] = useState<Client[]>(initialClients)
  const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
  const total = useMemo(() => items.reduce((sum, item) => sum + item.quantity * item.unit, 0) + travel, [items, travel])
  const equipment = useMemo(() => items.filter(i => i.kind === 'equipment').reduce((s, i) => s + i.quantity * i.unit, 0), [items])
  const labor = useMemo(() => items.filter(i => i.kind === 'service').reduce((s, i) => s + i.quantity * i.unit, 0), [items])
  const update = (index: number, patch: Partial<Item>) => setItems(current => current.map((item, i) => i === index ? { ...item, ...patch } : item))
  const nextOs = () => { const year = new Date().getFullYear(); const key = `rooted-os-counter-${year}`; const next = Number(localStorage.getItem(key) || '0') + 1; localStorage.setItem(key, String(next)); return `OS-${year}-${String(next).padStart(4, '0')}` }
  const applyClient = (entry: Client) => { setClient(entry.name); setPhone(entry.phone); setDescription(entry.description); setItems(entry.items.length ? entry.items.map(item => ({ ...item })) : [emptyItem()]); setShowClientBase(false); setMessage(entry.items.length ? 'Cliente de demonstração carregado com 4 produtos e 4 serviços.' : 'Cliente aplicado ao orçamento.') }
  const addCatalogItem = (entry: CatalogEntry, kind: Kind) => { setItems(current => [...current.filter(i => i.name), { name: entry.name, quantity: 1, unit: entry.unit, source: 'rooted', kind }]); setMessage(`${entry.name} adicionado ao orçamento.`) }
  const saveClient = () => { if (!client.trim()) return setMessage('Digite o nome do cliente antes de cadastrar.'); setClients(current => [...current.filter(c => c.name !== client.trim()), { name: client.trim(), phone, description, items }]); setMessage('Cliente salvo na base local do navegador.'); setShowClientBase(false) }
  const newBudget = () => { setClient(''); setPhone(''); setDescription(''); setTravel(0); setItems([emptyItem()]); setMarkup(30); setPayment('PIX / Mercado Pago'); setResponsible('Roberto Jean Martins'); setOs(nextOs()); setStatus('Rascunho'); setSaved(false); setMessage('Novo orçamento criado.') }
  useEffect(() => { const storedClients = localStorage.getItem('rooted-clientes'); if (storedClients) { try { setClients(JSON.parse(storedClients)) } catch {} } const draft = localStorage.getItem('rooted-orcamento-draft'); if (draft) { try { const d = JSON.parse(draft); setClient(d.client || ''); setOs(d.os || nextOs()); setResponsible(d.responsible || 'Roberto Jean Martins'); setPhone(d.phone || ''); setPayment(d.payment || 'PIX / Mercado Pago'); setDescription(d.description || ''); setMarkup(typeof d.markup === 'number' ? d.markup : 30); setTravel(typeof d.travel === 'number' ? d.travel : 0); setItems(Array.isArray(d.items) ? d.items : [emptyItem()]); setStatus(d.status || 'Rascunho') } catch { setOs(nextOs()) } } else setOs(nextOs()); if (API_URL) loadHistory() }, [])
  useEffect(() => { localStorage.setItem('rooted-clientes', JSON.stringify(clients)) }, [clients])
  async function loadHistory() { if (!API_URL) return; try { const response = await fetch(`${API_URL}/orcamentos.php`); if (!response.ok) throw new Error(); const json = await response.json(); setHistory(json.data || []) } catch { setMessage('Histórico PHP indisponível; o modo local continua funcionando.') } }
  const saveDraft = async () => { const data = { client, os, responsible, phone, payment, description, markup, travel, items, total, warranty, status: 'Salvo localmente', updatedAt: new Date().toISOString() }; localStorage.setItem('rooted-orcamento-draft', JSON.stringify(data)); setSaved(true); setStatus('Salvo localmente'); setMessage('Orçamento salvo no navegador.'); if (API_URL) { try { const response = await fetch(`${API_URL}/orcamentos.php`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...data, cliente: client }) }); if (!response.ok) throw new Error(); setMessage('Orçamento salvo no navegador e no banco PHP/MySQL.'); await loadHistory() } catch { setMessage('Salvo localmente. A API PHP não respondeu.') } } }
  const loadBudget = (row: any) => { setClient(row.cliente || ''); setOs(row.os || ''); setResponsible(row.responsavel || ''); setPhone(row.telefone || ''); setPayment(row.pagamento || ''); setDescription(row.descricao || ''); setMarkup(Number(row.markup || 30)); setTravel(Number(row.deslocamento || 0)); setItems(row.itens || [emptyItem()]); setStatus(row.status || 'Rascunho'); setSaved(false); setMessage('Orçamento carregado do banco.') }
  const exportText = () => { const text = `ROOTED INFORMÁTICA\nORÇAMENTO ${os || 'SEM OS'}\nCliente: ${client}\nTelefone: ${phone}\nResponsável: ${responsible}\nDescrição: ${description}\n\nITENS\n${items.filter(i => i.name).map(i => `${i.quantity}x ${i.name} | ${money(i.unit)} | ${i.source === 'client' ? 'Cliente' : 'Rooted'}`).join('\n')}\n\nEquipamentos: ${money(equipment)}\nMão de obra/serviços: ${money(labor)}\nDeslocamento: ${money(travel)}\nTotal geral: ${money(total)}\nForma de pagamento: ${payment}\n\n${warranty}`; const blob = new Blob([text], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `orcamento-${os || 'sem-os'}.txt`; a.click(); URL.revokeObjectURL(url) }

  return <main className="shell"><header className="header"><div><div className="brand">ROOTED <span>ORÇAMENTOS IA</span></div><div className="muted">Propostas profissionais • emissão rápida • controle de clientes</div></div><div className="header-actions"><span className="tag">{status}</span><button className="button secondary" onClick={newBudget}>+ Novo orçamento</button><button className="button" onClick={saveDraft}>Salvar orçamento</button></div></header><div className="notice"><b>Modo demonstração:</b> selecione o cliente completo para preencher automaticamente os 4 produtos e 4 serviços.</div>
    <section className="grid"><div className="panel"><div className="section-heading"><div><h2>Dados do orçamento</h2><p className="muted">Use os cadastros prontos para testar a emissão.</p></div><span className="step">01</span></div><div className="actions compact"><button className="button" onClick={() => setShowClientBase(value => !value)}>👤 Base de clientes</button><button className="button secondary" onClick={() => setOs(nextOs())}>Gerar nova OS</button></div>
      {showClientBase && <div className="quick-client"><div className="quick-title"><b>Base local de clientes</b><span>O cliente completo preenche tudo para o teste</span></div><div className="catalog-list">{clients.map((entry, index) => <button className="catalog-row" key={`${entry.name}-${index}`} onClick={() => applyClient(entry)}><span>{entry.name}<small>{entry.phone}{entry.items.length ? ` • ${entry.items.filter(i => i.kind === 'equipment').length} produtos + ${entry.items.filter(i => i.kind === 'service').length} serviços` : ''}</small></span><b>Usar</b></button>)}</div><button className="button" onClick={saveClient}>Salvar cliente atual</button></div>}
      <div className="form-grid"><div className="field"><label>Cliente</label><input value={client} onChange={e => setClient(e.target.value)} placeholder="Nome ou empresa" /></div><div className="field"><label>Ordem de serviço automática</label><input value={os} onChange={e => setOs(e.target.value)} /></div><div className="field"><label>Telefone</label><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="(41) 99999-9999" /></div><div className="field"><label>Responsável técnico</label><input value={responsible} onChange={e => setResponsible(e.target.value)} /></div></div><div className="field"><label>Descrição do serviço</label><textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Descrição preenchida pelo cliente de demonstração..." /></div>
      <div className="section-heading"><div><h2>Itens orçados</h2><p className="muted">Produtos e serviços carregados automaticamente.</p></div><span className="step">02</span></div><div className="actions compact"><button className="button" onClick={() => setShowProductBase(value => !value)}>📦 Base de produtos</button><button className="button secondary" onClick={() => setShowServiceBase(value => !value)}>🛠 Base de serviços</button></div>{showProductBase && <div className="catalog-box"><b>Produtos</b>{products.map((entry, index) => <button className="catalog-row" key={`${entry.name}-${index}`} onClick={() => addCatalogItem(entry, 'equipment')}><span>{entry.name}<small>{money(entry.unit)}</small></span><b>+ Adicionar</b></button>)}</div>}{showServiceBase && <div className="catalog-box"><b>Serviços</b>{services.map((entry, index) => <button className="catalog-row" key={`${entry.name}-${index}`} onClick={() => addCatalogItem(entry, 'service')}><span>{entry.name}<small>{money(entry.unit)}</small></span><b>+ Adicionar</b></button>)}</div>}
      {items.map((item, index) => <div className="item" key={index}><div className="item-top"><b>Item {index + 1}</b><span>{money(item.quantity * item.unit)}</span></div><div className="field"><label>Produto ou serviço</label><input value={item.name} onChange={e => update(index, { name: e.target.value })} placeholder="Ex.: Câmera de segurança" /></div><div className="item-grid"><div className="field"><label>Quantidade</label><input type="number" min="1" value={item.quantity} onChange={e => update(index, { quantity: Math.max(1, Number(e.target.value) || 1) })} /></div><div className="field"><label>Valor unitário (R$)</label><input type="number" min="0" step="0.01" value={item.unit} onChange={e => update(index, { unit: Math.max(0, Number(e.target.value) || 0) })} /></div><div className="field"><label>Origem</label><select value={item.source} onChange={e => update(index, { source: e.target.value as Source })}><option value="rooted">Rooted</option><option value="client">Cliente</option></select></div><div className="field"><label>Categoria</label><select value={item.kind} onChange={e => update(index, { kind: e.target.value as Kind })}><option value="equipment">Equipamento/material</option><option value="service">Serviço</option></select></div></div></div>)}
      <div className="actions"><button className="button" onClick={() => setItems(current => [...current, emptyItem()])}>+ Item manual</button><button className="button secondary" onClick={() => setItems(current => current.length > 1 ? current.slice(0, -1) : current)}>Remover último</button></div><div className="form-grid"><div className="field"><label>Deslocamento (R$)</label><input type="number" min="0" step="0.01" value={travel} onChange={e => setTravel(Math.max(0, Number(e.target.value) || 0))} /></div><div className="field"><label>Forma de pagamento</label><select value={payment} onChange={e => setPayment(e.target.value)}><option>PIX / Mercado Pago</option><option>À vista</option><option>Cartão</option><option>Boleto</option><option>A combinar</option></select></div><div className="field"><label>Markup informativo (%)</label><input type="number" min="0" value={markup} onChange={e => setMarkup(Math.max(0, Number(e.target.value) || 0))} /></div></div><div className="actions"><button className="button" onClick={saveDraft}>Salvar</button><button className="button secondary" onClick={exportText}>Exportar TXT</button><button className="button secondary" onClick={() => window.print()}>Gerar PDF / Imprimir</button><button className="button secondary" onClick={newBudget}>Novo</button></div>{message && <div className="notice">{message}</div>}</div>
      <aside className="panel preview"><div className="section-heading"><div><h2>Prévia do orçamento</h2><p className="muted">Confira os dados antes de gerar o PDF.</p></div><span className="step">03</span></div><div className="preview-head"><b>ROOTED INFORMÁTICA</b><span>{os || 'OS não informada'}</span></div><p><b>Cliente:</b> {client || 'Não informado'}</p><p><b>Telefone:</b> {phone || 'Não informado'}</p><p><b>Responsável:</b> {responsible || 'Não informado'}</p><p><b>Descrição:</b> {description || 'Ainda não preenchida'}</p><div className="summary"><div className="muted">Total geral</div><strong>{money(total)}</strong><div className="line"><span>Equipamentos e materiais</span><b>{money(equipment)}</b></div><div className="line"><span>Mão de obra e serviços</span><b>{money(labor)}</b></div><div className="line"><span>Deslocamento</span><b>{money(travel)}</b></div><div className="line"><span>Markup informado</span><b>{markup}%</b></div></div><h3>Itens incluídos</h3>{items.filter(i => i.name).map((item, index) => <div className="line" key={index}><span>{item.quantity}x {item.name}</span><b>{money(item.quantity * item.unit)}</b></div>)}<h3>Garantia</h3><p className="small preserve">{warranty}</p>{API_URL && <><h3>Histórico do banco</h3><button className="button secondary" onClick={loadHistory}>Atualizar histórico</button><div className="history-list">{history.map(row => <button className="line" key={row.id} onClick={() => loadBudget(row)}><span>#{row.id} {row.cliente}</span><b>{money(Number(row.total))}</b></button>)}</div></>}<div className="notice">{saved ? 'Orçamento salvo localmente.' : 'Revise os campos antes de emitir o documento.'}</div></aside></section><footer className="footer">ROOTED INFORMÁTICA • Sistema de orçamentos • versão de trabalho</footer></main>
}
