CREATE DATABASE IF NOT EXISTS rooted_orcamentos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rooted_orcamentos;

CREATE TABLE IF NOT EXISTS orcamentos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  os VARCHAR(80) NULL,
  cliente VARCHAR(180) NOT NULL,
  telefone VARCHAR(40) NULL,
  responsavel VARCHAR(180) NULL,
  pagamento VARCHAR(80) NULL,
  descricao TEXT NULL,
  markup DECIMAL(10,2) NOT NULL DEFAULT 30,
  deslocamento DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'Rascunho',
  itens JSON NOT NULL,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
